runtime: python38
entrypoint: gunicorn -b :$PORT app:app
handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto
env_variables:
  DB_HOST: 35.199.66.87
  DB_PORT: 5432
  DB_NAME: viabrasil
  DB_PASS: 1234
  DB_USERNAME: postgres